language: python
python:
- 3.5
install:
- pip3 install tox
script:
- tox
notifications:
  slack:
    secure: FW3fsWxJMmw++FNjFFc2goD318V/kV/ez21vTKT4PbWJi4FL1doFDkWcHnIL0o3M1YBu4gwtFfV6sGAhdILIk5R3BgqAa0i61ez4nhIr/WD6otdvVrqcHqcZ33XsblefDDx9EFaGYxvx9Q0QcPykGwFF4f5Rfzqk53nZceHNDOvDGZi9n14MAFy9nXsax80/vE//cgNP/+DQUCIKpTlwcMsKX7dlDsLI2LfLQfFc0WepJgpjncHkYIQ5A1MxPIUtxe8MDuyYiNdmhcT7hCTHyQgxjlVXzKG2Xd4sr1c3nlovVJfKd/hCJvDeOCzvUmehOrS9wdStTlc6np3cve5x/3Hr6Jcaz4ckpkcP4ytA9UPeh52q+tVbCqVFW3xjyPTXL6hNla4E8MG7oy7DA6YyJZ0aWgI5ePOOgadFKVcR2tdEvznx5H77JCF+bmEgIo2Zrz1UXl7ERGh/BGAQTEex7LHrsAKAw3f6xYb8O+OUTt/xWjKmaKJNMGqSuAiNzzvlxdyfB6lgP7GfoDZGkL8Pld3XWxMhLaZ5tsJ7AaAWxP3cpD+NVey4hDKWoZYTVzSmQ4ScXwDfOMQMPQ7rnD6wWzpIJMk3/LmCedTKgf428IKcPazlkVkv1FI2sx9hl2jz2bMwkqfEcSc30wbpZLF6VoakZbOmcSjDFNeJLog1YS4=
